{% set name = "lightning" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-{{ version }}.tar.gz
  sha256: 4f56a390e58551cf40173c8c74684972c261185f3a92690888340b7209855f49

build:
  entry_points:
    - lightning = lightning.app.cli.lightning_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - arrow <1.2.4,>=1.2.0
    - beautifulsoup4 <4.11.2,>=4.8.0
    - click <=8.1.3
    - croniter <1.4.0,>=1.3.0
    - deepdiff <6.2.3,>=5.7.0
    - fsspec <2022.7.1,>=2022.5.0
    - inquirer >=2.10.0
    - lightning-cloud >=0.5.12
    - lightning-utilities <0.5.0,>=0.3.0,!=0.4.0
    - packaging
    - psutil <5.9.4
    - python >=3.7
    - pytorch-lightning
    - starsessions <2.0,>=1.2.1
    - traitlets <=5.4.0,>=5.3.0
    - typing-extensions <=4.4.0,>=4.0.0

test:
  imports:
    - lightning
  commands:
    - pip check
    - LIGHTING_TESTING=1 lightning --help
  requires:
    - pip
    - python >=3.7, <3.11 # TODO: this upper bound is because of PyTorch issue with dataclass

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_file:
    - LICENSE
    - src/lightning/app/cli/component-template/LICENSE
    - src/lightning/app/cli/app-template/LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
